### PR TITLE
Sets default virtualizationType to HVM if none are retrieved from API

### LINKED ISSUE #282: No spot found when limiting to new 'd' instances
# Github issue #

## Issue type ##

- Bug Report

## Build number #

Installed 0.0.9 from the terraform registry

```text
nightly-888
```

## Configuration ##

Here is the TF used to launch the stack:

```
module "autospotting" {
  source  = "cristim/autospotting/aws"
  version = "0.0.9" # this version is subject to change
  autospotting_allowed_instance_types = "m5d.*,c5d.*,r5d.*"
  autospotting_regions_enabled = "us-west-2"
}
```

## Environment ##

- AWS region
us-west-2
- Type of environment: (VPC, EC2Classic or DefaultVPC)
VPC

## Summary ##

When limiting `autospotting_allowed_instance_types` to only the new 'd' type instances, autospotting can no longer find a replacement spot instance to launch.

## Steps to reproduce ##

Install autospotting via terraform, using config shown above.
Tag an ASG of m5d.large instances with the following tags:
```
tag {
    key = "spot-enabled"
    value = "true"
    propagate_at_launch = false
  }
  tag {
    key = "autospotting_min_on_demand_percentage"
    value = "33.3"
    propagate_at_launch = false
  }
```

## Expected results ##

I expect to have my m5d.large instances replaced with other 'd' type spot instances.

## Actual results ##

autospotting was unable to fulfill the request, even though spot pricing for an m5d.large instance is way lower than on-demand pricing.

```text
START RequestId: f9d7c5b6-8e9c-11e8-ae1c-154c208865fd Version: $LATEST
2018/07/23 17:22:29 Starting autospotting agent, build nightly-888
2018/07/23 17:22:29 Parsed command line flags: regions='us-west-2' min_on_demand_number=0 min_on_demand_percentage=0.0 allowed_instance_types=m5d.*,c5d.*,r5d.* disallowed_instance_types= on_demand_price_multiplier=1.00 spot_price_buffer_percentage=10.000 bidding_policy=normal tag_filters= tag_filter_mode=opt-in spot_product_description=Linux/UNIX (Amazon VPC)
2018/07/23 17:22:29 main.go:123: Scanning for available AWS regions
2018/07/23 17:22:30 main.go:95: Enabled to run in us-west-2, processing region.
2018/07/23 17:22:30 region.go:74: Creating connections to the required AWS services in us-west-2
2018/07/23 17:22:30 connections.go:29: Creating Service connections in us-west-2
2018/07/23 17:22:30 connections.go:43: Created service connections in us-west-2
2018/07/23 17:22:30 region.go:81: Scanning for enabled AutoScaling groups in us-west-2
2018/07/23 17:22:30 region.go:352: Processing page 1 of DescribeAutoScalingGroupsPages for us-west-2
2018/07/23 17:22:30 region.go:331: Enabling group sk-cattle-asg-stg for processing because its tags, the currently configured filtering mode (opt-in) and tag filters are aligned
2018/07/23 17:22:30 region.go:331: Enabling group sk-datacollection-cattle-asg-stg for processing because its tags, the currently configured filtering mode (opt-in) and tag filters are aligned
2018/07/23 17:22:30 region.go:325: Skipping group sk-rabbitmq-stg because its tags, the currently configured filtering mode (opt-in) and tag filters do not align
2018/07/23 17:22:30 region.go:325: Skipping group sk-sphinx-asg-stg because its tags, the currently configured filtering mode (opt-in) and tag filters do not align
2018/07/23 17:22:30 region.go:88: Scanning full instance information in us-west-2
2018/07/23 17:22:30 spot_price.go:21: us-west-2 Requesting spot prices
2018/07/23 17:22:30 region.go:93: Scanning instances in us-west-2
2018/07/23 17:22:30 region.go:160: Processing page 1 of DescribeInstancesPages for us-west-2
2018/07/23 17:22:30 region.go:99: Processing enabled AutoScaling groups in us-west-2
2018/07/23 17:22:30 autoscaling.go:358: Adding instances to sk-datacollection-cattle-asg-stg
2018/07/23 17:22:30 autoscaling.go:358: Adding instances to sk-cattle-asg-stg
2018/07/23 17:22:30 autoscaling.go:247: No default value for on-demand instances specified, skipping.
2018/07/23 17:22:30 autoscaling.go:319: Finding spot instances created for sk-datacollection-cattle-asg-stg
2018/07/23 17:22:30 autoscaling.go:324: No spot instances were found for sk-datacollection-cattle-asg-stg
2018/07/23 17:22:30 autoscaling.go:247: No default value for on-demand instances specified, skipping.
2018/07/23 17:22:30 autoscaling.go:88: Loaded MinOnDemand value to 2 from tag autospotting_min_on_demand_percentage
2018/07/23 17:22:30 autoscaling.go:197: Found and applied configuration for OnDemand value
2018/07/23 17:22:30 autoscaling.go:319: Finding spot instances created for sk-cattle-asg-stg
2018/07/23 17:22:30 autoscaling.go:324: No spot instances were found for sk-cattle-asg-stg
2018/07/23 17:22:30 instance.go:267: Comparing c4.xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing i3.8xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m1.xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing c3.large with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing c4.large with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m2.4xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing g3.4xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m5.24xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing c5.4xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing g3.16xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing d2.8xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing i2.2xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing x1.32xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing p2.xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m1.medium with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing x1e.32xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing g3.8xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m3.medium with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing c3.8xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing p3.2xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing i3.metal with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing i2.xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m5.xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing c5d.large with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing r4.2xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing i3.large with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing i2.4xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing t2.medium with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing x1e.4xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing r3.2xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing t2.xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m5d.xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing cc2.8xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing c3.2xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing g2.8xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing i3.16xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m3.2xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing c1.xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing f1.16xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing c1.medium with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing i2.8xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing t1.micro with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing i3.xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing c5d.18xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing r4.8xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m5d.2xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing c5d.2xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing c5d.4xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing p3.8xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing p2.16xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing c3.xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m2.2xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing t2.micro with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing h1.4xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing t2.small with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m5.4xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing r4.large with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m5d.12xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing x1e.16xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing c5.18xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing p3.16xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing d2.2xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing r3.4xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing t2.large with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m4.4xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing d2.4xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing c3.4xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m4.large with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing c5d.9xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m5.12xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m4.10xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m1.small with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m2.xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing r3.large with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m5d.4xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing c5.9xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing i3.4xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing h1.8xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m4.16xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing c4.2xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing f1.2xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m5d.large with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing x1.16xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing r4.xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m3.xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing cr1.8xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing t2.nano with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing x1e.8xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing d2.xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing c5.large with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing c5.xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing x1e.2xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing h1.16xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing g2.2xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing r3.xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing r4.16xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m4.2xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing c5d.xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing x1e.xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m5.2xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m5d.24xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m4.xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing h1.2xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing hs1.8xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing t2.2xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing c5.2xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m3.large with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m5.large with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing r4.4xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing p2.8xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing r3.8xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing c4.4xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing i3.2xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m1.large with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing c4.8xlarge with m5d.large
2018/07/23 17:22:30 instance.go:299: Couldn't determine the cheapest compatible spot instance type
2018/07/23 17:22:30 autoscaling.go:337: Could not launch cheapest spot instance: No cheaper spot instance types could be found
2018/07/23 17:22:30 instance.go:267: Comparing c4.2xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing f1.2xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing h1.8xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m4.16xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing cr1.8xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing t2.nano with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m5d.large with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing x1.16xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing r4.xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m3.xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing c5.xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing x1e.2xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing x1e.8xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing d2.xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing c5.large with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing r3.xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing r4.16xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing h1.16xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing g2.2xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m5d.24xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m4.xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m4.2xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing c5d.xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing x1e.xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m5.2xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing t2.2xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing c5.2xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing h1.2xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing hs1.8xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m5.large with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing r4.4xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m3.large with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing p2.8xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing c4.4xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing i3.2xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing r3.8xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing c4.8xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m1.large with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing c3.large with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing c4.large with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing c4.xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing i3.8xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m1.xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing g3.4xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m2.4xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing c5.4xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m5.24xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing x1.32xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing p2.xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing g3.16xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing d2.8xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing i2.2xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing x1e.32xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m1.medium with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing c3.8xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing p3.2xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing g3.8xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m3.medium with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m5.xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing c5d.large with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing i3.metal with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing i2.xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing t2.medium with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing x1e.4xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing r4.2xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing i3.large with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing i2.4xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing c3.2xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing g2.8xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing r3.2xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing t2.xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m5d.xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing cc2.8xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing c1.xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing f1.16xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing i3.16xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m3.2xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing i2.8xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing c1.medium with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing i3.xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing t1.micro with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing r4.8xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing c5d.18xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m2.2xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing t2.micro with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m5d.2xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing c5d.2xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing c5d.4xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing p3.8xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing p2.16xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing c3.xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing h1.4xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m5.4xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing r4.large with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing t2.small with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing x1e.16xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m5d.12xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing t2.large with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m4.4xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing c5.18xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing p3.16xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing d2.2xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing r3.4xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m4.large with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing c5d.9xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing d2.4xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing c3.4xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m5.12xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m2.xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing r3.large with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m4.10xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m1.small with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing c5.9xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing i3.4xlarge with m5d.large
2018/07/23 17:22:30 instance.go:267: Comparing m5d.4xlarge with m5d.large
2018/07/23 17:22:30 instance.go:299: Couldn't determine the cheapest compatible spot instance type
2018/07/23 17:22:30 autoscaling.go:337: Could not launch cheapest spot instance: No cheaper spot instance types could be found
2018/07/23 17:22:30 Execution completed, nothing left to do
END RequestId: f9d7c5b6-8e9c-11e8-ae1c-154c208865fd
REPORT RequestId: f9d7c5b6-8e9c-11e8-ae1c-154c208865fd	Duration: 701.64 ms	Billed Duration: 800 ms Memory Size: 1024 MB	Max Memory Used: 52 MB
```

### PR DESCRIPTION
**Pull request by drpebcak**
Meant to address and resolve #282

### CODE REVIEW

**Comment by drpebcak** [comment]
There seems to be some issue with travis that is probably unrelated to this PR.

File: core/instance.go [hunk 1]
```diff
@@ -269,6 +269,9 @@ func (i *instance) getCheapestCompatibleSpotInstanceType(allowedList []string, d
 
 		candidatePrice := i.calculatePrice(candidate)
 
+		if len(candidate.virtualizationTypes) == 0 {
+			candidate.virtualizationTypes = append(candidate.virtualizationTypes, "HVM")
+		}
```
Comment (xlr-8) [inline core/instance.go]: I'd rather have that move to [the method comparing virtualization](https://github.com/cristim/autospotting/blob/master/core/instance.go#L213) - because it's directly related to visualization comparison, and if we have more exception, this method will become unmaintainable.

**Comment by xlr-8** [comment]
> There seems to be some issue with travis that is probably unrelated to this PR.

I confirm the travis failing isn't due to the changes in this PR, most likely due to a network / git issue of some sort. I re-triggered it and it passed fine.

File: core/instance.go (hunk 1 above)
Comment (xlr-8) [reply core/instance.go]: Also there are no tests for this condition.

Comment (drpebcak) [reply core/instance.go]: Yeah that makes sense. I moved it and added a test case for it.

**Comment by drpebcak** [comment]
@xlr-8 can you take another look?

File: core/instance.go [hunk 2]
```diff
@@ -212,7 +212,9 @@ func (i *instance) isStorageCompatible(spotCandidate instanceTypeInformation, at
 
 func (i *instance) isVirtualizationCompatible(spotVirtualizationTypes []string) bool {
 	current := *i.VirtualizationType
-
+	if len(spotVirtualizationTypes) == 0 {
+		spotVirtualizationTypes = append(spotVirtualizationTypes, "HVM")
```
Comment (cristim) [inline core/instance.go]: I think `[]string{"HVM"}` would be better than the append

Comment (drpebcak) [reply core/instance.go]: @cristim done

**Comment by cristim** [comment]
LGTM, @xlr-8 do you have any other concerns?
