### PR TITLE
In progress: Enable EBS pricing and automatically turn on if free

### LINKED ISSUE #115: Autospotting Selects Incompatible Instance: EBS Optimization
# Github issue #
If a launch config has EBS optimization enabled it is possible for autospotting to select an instance that does not have EBS optimization.  This results in a failed spot request. 

## Issue type ##

- Bug Report

## Build number #

```text
```

## Environment ##

- AWS region
- Type of environment: (VPC, EC2Classic or DefaultVPC)
- Anonymized launch configuration: 

```text
```

## Actual results ##

```text
```

### PR DESCRIPTION
**Pull request by vecchp**
# Issue Type #

- Feature Pull Request
- Bug fix
## Summary ##
- Include EBS surcharging in price calculation. 
- Turn on EBS optimization if it is free. ( Implements #88 )
- Fix bug where launch config has EBS enabled but Autospotting selects an instance which does not have the capability. ( Fixes #115 )

```text
```

### CODE REVIEW

**Comment by vecchp** [comment]
@cristim , this should be ready to be merged.

File: core/instance.go [hunk 1]
```diff
@@ -225,12 +242,15 @@ func (i *instance) getCheapestCompatibleSpotInstanceType() (string, error) {
 		logger.Println("Comparing ", candidate.instanceType, " with ",
 			current.instanceType)
 
+		currentPrice := i.calculatePrice(candidate)
```
Comment (cristim) [inline core/instance.go]: I would like to have this named something like candidatePrice, in order to match the naming of the candidate variable used in this block of code.

**Comment by cristim** [comment]
@vecchp thanks for your contribution to the project, I'm looking forward for more 😀
